# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: windows-latest

steps:
  - task: NodeTool@0
    displayName: 'Use Node 12.16.1 (LTS)'
    inputs:
      versionSpec: '12.16.1'
      checkLatest: true

  - script: npm cache clean --force
    displayName: 'npm cache clean'

  - script: npm install
    displayName: 'npm install'

  - script: npm start
    displayName: 'Starting Script'
  